/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author some
 */
public class GUIPanel extends javax.swing.JPanel {
    
    private int motorA;
    private int motorB;
    private int motorC;
    /**
     * Creates new form GUIPanel
     */
    public GUIPanel() {
        motorA = 0;
        motorB = 0;
        motorC = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slMotorA = new javax.swing.JSlider();
        slMotorB = new javax.swing.JSlider();
        slMotorC = new javax.swing.JSlider();
        btnMotorA = new javax.swing.JButton();
        btnMotorB = new javax.swing.JButton();
        btnMotorC = new javax.swing.JButton();
        motorAValue = new javax.swing.JLabel();
        motorBValue = new javax.swing.JLabel();
        motorCValue = new javax.swing.JLabel();
        btnHalt = new javax.swing.JButton();
        btnAllOk = new javax.swing.JButton();

        jLabel1.setText("Motor A");

        jLabel2.setText("Motor B");

        jLabel3.setText("Motor C");

        slMotorA.setMinimum(-100);
        slMotorA.setValue(0);
        slMotorA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slMotorAStateChanged(evt);
            }
        });

        slMotorB.setMinimum(-100);
        slMotorB.setValue(0);
        slMotorB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slMotorBStateChanged(evt);
            }
        });

        slMotorC.setMinimum(-100);
        slMotorC.setValue(0);
        slMotorC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slMotorCStateChanged(evt);
            }
        });

        btnMotorA.setText("OK");
        btnMotorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotorAActionPerformed(evt);
            }
        });

        btnMotorB.setText("OK");
        btnMotorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotorBActionPerformed(evt);
            }
        });

        btnMotorC.setText("OK");
        btnMotorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotorCActionPerformed(evt);
            }
        });

        motorAValue.setText("0");

        motorBValue.setText("0");

        motorCValue.setText("0");

        btnHalt.setText("HALT");
        btnHalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaltActionPerformed(evt);
            }
        });

        btnAllOk.setText("Alle OK");
        btnAllOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slMotorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(motorBValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slMotorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(motorAValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHalt)
                                .addGap(27, 27, 27)
                                .addComponent(btnAllOk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slMotorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(motorCValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMotorB)
                    .addComponent(btnMotorA)
                    .addComponent(btnMotorC))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slMotorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMotorA)
                        .addComponent(motorAValue)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(slMotorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMotorB)
                        .addComponent(motorBValue)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slMotorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMotorC)
                        .addComponent(motorCValue)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHalt)
                    .addComponent(btnAllOk))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorAActionPerformed
        //System.out.println("Motor A: " + slMotorA.getValue());
        motorA = slMotorA.getValue();
    }//GEN-LAST:event_btnMotorAActionPerformed

    private void btnMotorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorBActionPerformed
        //System.out.println("Motor B: " + slMotorB.getValue());
        motorB = slMotorB.getValue();
    }//GEN-LAST:event_btnMotorBActionPerformed

    private void btnMotorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotorCActionPerformed
        //System.out.println("Motor C: " + slMotorC.getValue());
        motorC = slMotorC.getValue();
    }//GEN-LAST:event_btnMotorCActionPerformed

    private void slMotorAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slMotorAStateChanged
        motorAValue.setText(""+slMotorA.getValue());
    }//GEN-LAST:event_slMotorAStateChanged

    private void slMotorBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slMotorBStateChanged
        motorBValue.setText(""+slMotorB.getValue());
    }//GEN-LAST:event_slMotorBStateChanged

    private void slMotorCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slMotorCStateChanged
        motorCValue.setText(""+slMotorC.getValue());
    }//GEN-LAST:event_slMotorCStateChanged

    private void btnHaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaltActionPerformed
        motorA = 0;
        motorB = 0;
        motorC = 0;
        slMotorA.setValue(0);
        slMotorB.setValue(0);
        slMotorC.setValue(0);
    }//GEN-LAST:event_btnHaltActionPerformed

    private void btnAllOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllOkActionPerformed
        motorA = slMotorA.getValue();
        motorB = slMotorB.getValue();
        motorC = slMotorC.getValue();
    }//GEN-LAST:event_btnAllOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllOk;
    private javax.swing.JButton btnHalt;
    private javax.swing.JButton btnMotorA;
    private javax.swing.JButton btnMotorB;
    private javax.swing.JButton btnMotorC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel motorAValue;
    private javax.swing.JLabel motorBValue;
    private javax.swing.JLabel motorCValue;
    private javax.swing.JSlider slMotorA;
    private javax.swing.JSlider slMotorB;
    private javax.swing.JSlider slMotorC;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the motorA
     */
    public int getMotorA() {
        return motorA;
    }

    /**
     * @return the motorB
     */
    public int getMotorB() {
        return motorB;
    }

    /**
     * @return the motorC
     */
    public int getMotorC() {
        return motorC;
    }
}
