// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: referee.proto

public final class Referee {
  private Referee() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SSL_RefereeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 packet_timestamp = 1;
    boolean hasPacketTimestamp();
    long getPacketTimestamp();
    
    // required .SSL_Referee.Stage stage = 2;
    boolean hasStage();
    Referee.SSL_Referee.Stage getStage();
    
    // optional sint32 stage_time_left = 3;
    boolean hasStageTimeLeft();
    int getStageTimeLeft();
    
    // required .SSL_Referee.Command command = 4;
    boolean hasCommand();
    Referee.SSL_Referee.Command getCommand();
    
    // required uint32 command_counter = 5;
    boolean hasCommandCounter();
    int getCommandCounter();
    
    // required uint64 command_timestamp = 6;
    boolean hasCommandTimestamp();
    long getCommandTimestamp();
    
    // required .SSL_Referee.TeamInfo yellow = 7;
    boolean hasYellow();
    Referee.SSL_Referee.TeamInfo getYellow();
    Referee.SSL_Referee.TeamInfoOrBuilder getYellowOrBuilder();
    
    // required .SSL_Referee.TeamInfo blue = 8;
    boolean hasBlue();
    Referee.SSL_Referee.TeamInfo getBlue();
    Referee.SSL_Referee.TeamInfoOrBuilder getBlueOrBuilder();
  }
  public static final class SSL_Referee extends
      com.google.protobuf.GeneratedMessage
      implements SSL_RefereeOrBuilder {
    // Use SSL_Referee.newBuilder() to construct.
    private SSL_Referee(Builder builder) {
      super(builder);
    }
    private SSL_Referee(boolean noInit) {}
    
    private static final SSL_Referee defaultInstance;
    public static SSL_Referee getDefaultInstance() {
      return defaultInstance;
    }
    
    public SSL_Referee getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Referee.internal_static_SSL_Referee_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Referee.internal_static_SSL_Referee_fieldAccessorTable;
    }
    
    public enum Stage
        implements com.google.protobuf.ProtocolMessageEnum {
      NORMAL_FIRST_HALF_PRE(0, 0),
      NORMAL_FIRST_HALF(1, 1),
      NORMAL_HALF_TIME(2, 2),
      NORMAL_SECOND_HALF_PRE(3, 3),
      NORMAL_SECOND_HALF(4, 4),
      EXTRA_TIME_BREAK(5, 5),
      EXTRA_FIRST_HALF_PRE(6, 6),
      EXTRA_FIRST_HALF(7, 7),
      EXTRA_HALF_TIME(8, 8),
      EXTRA_SECOND_HALF_PRE(9, 9),
      EXTRA_SECOND_HALF(10, 10),
      PENALTY_SHOOTOUT_BREAK(11, 11),
      PENALTY_SHOOTOUT(12, 12),
      POST_GAME(13, 13),
      ;
      
      public static final int NORMAL_FIRST_HALF_PRE_VALUE = 0;
      public static final int NORMAL_FIRST_HALF_VALUE = 1;
      public static final int NORMAL_HALF_TIME_VALUE = 2;
      public static final int NORMAL_SECOND_HALF_PRE_VALUE = 3;
      public static final int NORMAL_SECOND_HALF_VALUE = 4;
      public static final int EXTRA_TIME_BREAK_VALUE = 5;
      public static final int EXTRA_FIRST_HALF_PRE_VALUE = 6;
      public static final int EXTRA_FIRST_HALF_VALUE = 7;
      public static final int EXTRA_HALF_TIME_VALUE = 8;
      public static final int EXTRA_SECOND_HALF_PRE_VALUE = 9;
      public static final int EXTRA_SECOND_HALF_VALUE = 10;
      public static final int PENALTY_SHOOTOUT_BREAK_VALUE = 11;
      public static final int PENALTY_SHOOTOUT_VALUE = 12;
      public static final int POST_GAME_VALUE = 13;
      
      
      public final int getNumber() { return value; }
      
      public static Stage valueOf(int value) {
        switch (value) {
          case 0: return NORMAL_FIRST_HALF_PRE;
          case 1: return NORMAL_FIRST_HALF;
          case 2: return NORMAL_HALF_TIME;
          case 3: return NORMAL_SECOND_HALF_PRE;
          case 4: return NORMAL_SECOND_HALF;
          case 5: return EXTRA_TIME_BREAK;
          case 6: return EXTRA_FIRST_HALF_PRE;
          case 7: return EXTRA_FIRST_HALF;
          case 8: return EXTRA_HALF_TIME;
          case 9: return EXTRA_SECOND_HALF_PRE;
          case 10: return EXTRA_SECOND_HALF;
          case 11: return PENALTY_SHOOTOUT_BREAK;
          case 12: return PENALTY_SHOOTOUT;
          case 13: return POST_GAME;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Stage>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Stage>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Stage>() {
              public Stage findValueByNumber(int number) {
                return Stage.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Referee.SSL_Referee.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Stage[] VALUES = {
        NORMAL_FIRST_HALF_PRE, NORMAL_FIRST_HALF, NORMAL_HALF_TIME, NORMAL_SECOND_HALF_PRE, NORMAL_SECOND_HALF, EXTRA_TIME_BREAK, EXTRA_FIRST_HALF_PRE, EXTRA_FIRST_HALF, EXTRA_HALF_TIME, EXTRA_SECOND_HALF_PRE, EXTRA_SECOND_HALF, PENALTY_SHOOTOUT_BREAK, PENALTY_SHOOTOUT, POST_GAME, 
      };
      
      public static Stage valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Stage(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:SSL_Referee.Stage)
    }
    
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      HALT(0, 0),
      STOP(1, 1),
      NORMAL_START(2, 2),
      FORCE_START(3, 3),
      PREPARE_KICKOFF_YELLOW(4, 4),
      PREPARE_KICKOFF_BLUE(5, 5),
      PREPARE_PENALTY_YELLOW(6, 6),
      PREPARE_PENALTY_BLUE(7, 7),
      DIRECT_FREE_YELLOW(8, 8),
      DIRECT_FREE_BLUE(9, 9),
      INDIRECT_FREE_YELLOW(10, 10),
      INDIRECT_FREE_BLUE(11, 11),
      TIMEOUT_YELLOW(12, 12),
      TIMEOUT_BLUE(13, 13),
      GOAL_YELLOW(14, 14),
      GOAL_BLUE(15, 15),
      ;
      
      public static final int HALT_VALUE = 0;
      public static final int STOP_VALUE = 1;
      public static final int NORMAL_START_VALUE = 2;
      public static final int FORCE_START_VALUE = 3;
      public static final int PREPARE_KICKOFF_YELLOW_VALUE = 4;
      public static final int PREPARE_KICKOFF_BLUE_VALUE = 5;
      public static final int PREPARE_PENALTY_YELLOW_VALUE = 6;
      public static final int PREPARE_PENALTY_BLUE_VALUE = 7;
      public static final int DIRECT_FREE_YELLOW_VALUE = 8;
      public static final int DIRECT_FREE_BLUE_VALUE = 9;
      public static final int INDIRECT_FREE_YELLOW_VALUE = 10;
      public static final int INDIRECT_FREE_BLUE_VALUE = 11;
      public static final int TIMEOUT_YELLOW_VALUE = 12;
      public static final int TIMEOUT_BLUE_VALUE = 13;
      public static final int GOAL_YELLOW_VALUE = 14;
      public static final int GOAL_BLUE_VALUE = 15;
      
      
      public final int getNumber() { return value; }
      
      public static Command valueOf(int value) {
        switch (value) {
          case 0: return HALT;
          case 1: return STOP;
          case 2: return NORMAL_START;
          case 3: return FORCE_START;
          case 4: return PREPARE_KICKOFF_YELLOW;
          case 5: return PREPARE_KICKOFF_BLUE;
          case 6: return PREPARE_PENALTY_YELLOW;
          case 7: return PREPARE_PENALTY_BLUE;
          case 8: return DIRECT_FREE_YELLOW;
          case 9: return DIRECT_FREE_BLUE;
          case 10: return INDIRECT_FREE_YELLOW;
          case 11: return INDIRECT_FREE_BLUE;
          case 12: return TIMEOUT_YELLOW;
          case 13: return TIMEOUT_BLUE;
          case 14: return GOAL_YELLOW;
          case 15: return GOAL_BLUE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Referee.SSL_Referee.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Command[] VALUES = {
        HALT, STOP, NORMAL_START, FORCE_START, PREPARE_KICKOFF_YELLOW, PREPARE_KICKOFF_BLUE, PREPARE_PENALTY_YELLOW, PREPARE_PENALTY_BLUE, DIRECT_FREE_YELLOW, DIRECT_FREE_BLUE, INDIRECT_FREE_YELLOW, INDIRECT_FREE_BLUE, TIMEOUT_YELLOW, TIMEOUT_BLUE, GOAL_YELLOW, GOAL_BLUE, 
      };
      
      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Command(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:SSL_Referee.Command)
    }
    
    public interface TeamInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string name = 1;
      boolean hasName();
      String getName();
      
      // required uint32 score = 2;
      boolean hasScore();
      int getScore();
      
      // required uint32 red_cards = 3;
      boolean hasRedCards();
      int getRedCards();
      
      // repeated uint32 yellow_card_times = 4 [packed = true];
      java.util.List<java.lang.Integer> getYellowCardTimesList();
      int getYellowCardTimesCount();
      int getYellowCardTimes(int index);
      
      // required uint32 yellow_cards = 5;
      boolean hasYellowCards();
      int getYellowCards();
      
      // required uint32 timeouts = 6;
      boolean hasTimeouts();
      int getTimeouts();
      
      // required uint32 timeout_time = 7;
      boolean hasTimeoutTime();
      int getTimeoutTime();
      
      // required uint32 goalie = 8;
      boolean hasGoalie();
      int getGoalie();
    }
    public static final class TeamInfo extends
        com.google.protobuf.GeneratedMessage
        implements TeamInfoOrBuilder {
      // Use TeamInfo.newBuilder() to construct.
      private TeamInfo(Builder builder) {
        super(builder);
      }
      private TeamInfo(boolean noInit) {}
      
      private static final TeamInfo defaultInstance;
      public static TeamInfo getDefaultInstance() {
        return defaultInstance;
      }
      
      public TeamInfo getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Referee.internal_static_SSL_Referee_TeamInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Referee.internal_static_SSL_Referee_TeamInfo_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required uint32 score = 2;
      public static final int SCORE_FIELD_NUMBER = 2;
      private int score_;
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getScore() {
        return score_;
      }
      
      // required uint32 red_cards = 3;
      public static final int RED_CARDS_FIELD_NUMBER = 3;
      private int redCards_;
      public boolean hasRedCards() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRedCards() {
        return redCards_;
      }
      
      // repeated uint32 yellow_card_times = 4 [packed = true];
      public static final int YELLOW_CARD_TIMES_FIELD_NUMBER = 4;
      private java.util.List<java.lang.Integer> yellowCardTimes_;
      public java.util.List<java.lang.Integer>
          getYellowCardTimesList() {
        return yellowCardTimes_;
      }
      public int getYellowCardTimesCount() {
        return yellowCardTimes_.size();
      }
      public int getYellowCardTimes(int index) {
        return yellowCardTimes_.get(index);
      }
      private int yellowCardTimesMemoizedSerializedSize = -1;
      
      // required uint32 yellow_cards = 5;
      public static final int YELLOW_CARDS_FIELD_NUMBER = 5;
      private int yellowCards_;
      public boolean hasYellowCards() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getYellowCards() {
        return yellowCards_;
      }
      
      // required uint32 timeouts = 6;
      public static final int TIMEOUTS_FIELD_NUMBER = 6;
      private int timeouts_;
      public boolean hasTimeouts() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getTimeouts() {
        return timeouts_;
      }
      
      // required uint32 timeout_time = 7;
      public static final int TIMEOUT_TIME_FIELD_NUMBER = 7;
      private int timeoutTime_;
      public boolean hasTimeoutTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getTimeoutTime() {
        return timeoutTime_;
      }
      
      // required uint32 goalie = 8;
      public static final int GOALIE_FIELD_NUMBER = 8;
      private int goalie_;
      public boolean hasGoalie() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getGoalie() {
        return goalie_;
      }
      
      private void initFields() {
        name_ = "";
        score_ = 0;
        redCards_ = 0;
        yellowCardTimes_ = java.util.Collections.emptyList();;
        yellowCards_ = 0;
        timeouts_ = 0;
        timeoutTime_ = 0;
        goalie_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasScore()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasRedCards()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasYellowCards()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTimeouts()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTimeoutTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasGoalie()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, score_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeUInt32(3, redCards_);
        }
        if (getYellowCardTimesList().size() > 0) {
          output.writeRawVarint32(34);
          output.writeRawVarint32(yellowCardTimesMemoizedSerializedSize);
        }
        for (int i = 0; i < yellowCardTimes_.size(); i++) {
          output.writeUInt32NoTag(yellowCardTimes_.get(i));
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeUInt32(5, yellowCards_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeUInt32(6, timeouts_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeUInt32(7, timeoutTime_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeUInt32(8, goalie_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, score_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, redCards_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < yellowCardTimes_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeUInt32SizeNoTag(yellowCardTimes_.get(i));
          }
          size += dataSize;
          if (!getYellowCardTimesList().isEmpty()) {
            size += 1;
            size += com.google.protobuf.CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          yellowCardTimesMemoizedSerializedSize = dataSize;
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(5, yellowCards_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(6, timeouts_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(7, timeoutTime_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(8, goalie_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static Referee.SSL_Referee.TeamInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Referee.SSL_Referee.TeamInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static Referee.SSL_Referee.TeamInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Referee.SSL_Referee.TeamInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements Referee.SSL_Referee.TeamInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Referee.internal_static_SSL_Referee_TeamInfo_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Referee.internal_static_SSL_Referee_TeamInfo_fieldAccessorTable;
        }
        
        // Construct using Referee.SSL_Referee.TeamInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          score_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          redCards_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          yellowCardTimes_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000008);
          yellowCards_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          timeouts_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          timeoutTime_ = 0;
          bitField0_ = (bitField0_ & ~0x00000040);
          goalie_ = 0;
          bitField0_ = (bitField0_ & ~0x00000080);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Referee.SSL_Referee.TeamInfo.getDescriptor();
        }
        
        public Referee.SSL_Referee.TeamInfo getDefaultInstanceForType() {
          return Referee.SSL_Referee.TeamInfo.getDefaultInstance();
        }
        
        public Referee.SSL_Referee.TeamInfo build() {
          Referee.SSL_Referee.TeamInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private Referee.SSL_Referee.TeamInfo buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          Referee.SSL_Referee.TeamInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public Referee.SSL_Referee.TeamInfo buildPartial() {
          Referee.SSL_Referee.TeamInfo result = new Referee.SSL_Referee.TeamInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.score_ = score_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.redCards_ = redCards_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            yellowCardTimes_ = java.util.Collections.unmodifiableList(yellowCardTimes_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.yellowCardTimes_ = yellowCardTimes_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000008;
          }
          result.yellowCards_ = yellowCards_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000010;
          }
          result.timeouts_ = timeouts_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000020;
          }
          result.timeoutTime_ = timeoutTime_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000040;
          }
          result.goalie_ = goalie_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Referee.SSL_Referee.TeamInfo) {
            return mergeFrom((Referee.SSL_Referee.TeamInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(Referee.SSL_Referee.TeamInfo other) {
          if (other == Referee.SSL_Referee.TeamInfo.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          if (other.hasRedCards()) {
            setRedCards(other.getRedCards());
          }
          if (!other.yellowCardTimes_.isEmpty()) {
            if (yellowCardTimes_.isEmpty()) {
              yellowCardTimes_ = other.yellowCardTimes_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureYellowCardTimesIsMutable();
              yellowCardTimes_.addAll(other.yellowCardTimes_);
            }
            onChanged();
          }
          if (other.hasYellowCards()) {
            setYellowCards(other.getYellowCards());
          }
          if (other.hasTimeouts()) {
            setTimeouts(other.getTimeouts());
          }
          if (other.hasTimeoutTime()) {
            setTimeoutTime(other.getTimeoutTime());
          }
          if (other.hasGoalie()) {
            setGoalie(other.getGoalie());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasScore()) {
            
            return false;
          }
          if (!hasRedCards()) {
            
            return false;
          }
          if (!hasYellowCards()) {
            
            return false;
          }
          if (!hasTimeouts()) {
            
            return false;
          }
          if (!hasTimeoutTime()) {
            
            return false;
          }
          if (!hasGoalie()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                score_ = input.readUInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                redCards_ = input.readUInt32();
                break;
              }
              case 32: {
                ensureYellowCardTimesIsMutable();
                yellowCardTimes_.add(input.readUInt32());
                break;
              }
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                while (input.getBytesUntilLimit() > 0) {
                  addYellowCardTimes(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                yellowCards_ = input.readUInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                timeouts_ = input.readUInt32();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000040;
                timeoutTime_ = input.readUInt32();
                break;
              }
              case 64: {
                bitField0_ |= 0x00000080;
                goalie_ = input.readUInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // required uint32 score = 2;
        private int score_ ;
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getScore() {
          return score_;
        }
        public Builder setScore(int value) {
          bitField0_ |= 0x00000002;
          score_ = value;
          onChanged();
          return this;
        }
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0;
          onChanged();
          return this;
        }
        
        // required uint32 red_cards = 3;
        private int redCards_ ;
        public boolean hasRedCards() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getRedCards() {
          return redCards_;
        }
        public Builder setRedCards(int value) {
          bitField0_ |= 0x00000004;
          redCards_ = value;
          onChanged();
          return this;
        }
        public Builder clearRedCards() {
          bitField0_ = (bitField0_ & ~0x00000004);
          redCards_ = 0;
          onChanged();
          return this;
        }
        
        // repeated uint32 yellow_card_times = 4 [packed = true];
        private java.util.List<java.lang.Integer> yellowCardTimes_ = java.util.Collections.emptyList();;
        private void ensureYellowCardTimesIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            yellowCardTimes_ = new java.util.ArrayList<java.lang.Integer>(yellowCardTimes_);
            bitField0_ |= 0x00000008;
           }
        }
        public java.util.List<java.lang.Integer>
            getYellowCardTimesList() {
          return java.util.Collections.unmodifiableList(yellowCardTimes_);
        }
        public int getYellowCardTimesCount() {
          return yellowCardTimes_.size();
        }
        public int getYellowCardTimes(int index) {
          return yellowCardTimes_.get(index);
        }
        public Builder setYellowCardTimes(
            int index, int value) {
          ensureYellowCardTimesIsMutable();
          yellowCardTimes_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addYellowCardTimes(int value) {
          ensureYellowCardTimesIsMutable();
          yellowCardTimes_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllYellowCardTimes(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureYellowCardTimesIsMutable();
          super.addAll(values, yellowCardTimes_);
          onChanged();
          return this;
        }
        public Builder clearYellowCardTimes() {
          yellowCardTimes_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        
        // required uint32 yellow_cards = 5;
        private int yellowCards_ ;
        public boolean hasYellowCards() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        public int getYellowCards() {
          return yellowCards_;
        }
        public Builder setYellowCards(int value) {
          bitField0_ |= 0x00000010;
          yellowCards_ = value;
          onChanged();
          return this;
        }
        public Builder clearYellowCards() {
          bitField0_ = (bitField0_ & ~0x00000010);
          yellowCards_ = 0;
          onChanged();
          return this;
        }
        
        // required uint32 timeouts = 6;
        private int timeouts_ ;
        public boolean hasTimeouts() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        public int getTimeouts() {
          return timeouts_;
        }
        public Builder setTimeouts(int value) {
          bitField0_ |= 0x00000020;
          timeouts_ = value;
          onChanged();
          return this;
        }
        public Builder clearTimeouts() {
          bitField0_ = (bitField0_ & ~0x00000020);
          timeouts_ = 0;
          onChanged();
          return this;
        }
        
        // required uint32 timeout_time = 7;
        private int timeoutTime_ ;
        public boolean hasTimeoutTime() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        public int getTimeoutTime() {
          return timeoutTime_;
        }
        public Builder setTimeoutTime(int value) {
          bitField0_ |= 0x00000040;
          timeoutTime_ = value;
          onChanged();
          return this;
        }
        public Builder clearTimeoutTime() {
          bitField0_ = (bitField0_ & ~0x00000040);
          timeoutTime_ = 0;
          onChanged();
          return this;
        }
        
        // required uint32 goalie = 8;
        private int goalie_ ;
        public boolean hasGoalie() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        public int getGoalie() {
          return goalie_;
        }
        public Builder setGoalie(int value) {
          bitField0_ |= 0x00000080;
          goalie_ = value;
          onChanged();
          return this;
        }
        public Builder clearGoalie() {
          bitField0_ = (bitField0_ & ~0x00000080);
          goalie_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:SSL_Referee.TeamInfo)
      }
      
      static {
        defaultInstance = new TeamInfo(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:SSL_Referee.TeamInfo)
    }
    
    private int bitField0_;
    // required uint64 packet_timestamp = 1;
    public static final int PACKET_TIMESTAMP_FIELD_NUMBER = 1;
    private long packetTimestamp_;
    public boolean hasPacketTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getPacketTimestamp() {
      return packetTimestamp_;
    }
    
    // required .SSL_Referee.Stage stage = 2;
    public static final int STAGE_FIELD_NUMBER = 2;
    private Referee.SSL_Referee.Stage stage_;
    public boolean hasStage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public Referee.SSL_Referee.Stage getStage() {
      return stage_;
    }
    
    // optional sint32 stage_time_left = 3;
    public static final int STAGE_TIME_LEFT_FIELD_NUMBER = 3;
    private int stageTimeLeft_;
    public boolean hasStageTimeLeft() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getStageTimeLeft() {
      return stageTimeLeft_;
    }
    
    // required .SSL_Referee.Command command = 4;
    public static final int COMMAND_FIELD_NUMBER = 4;
    private Referee.SSL_Referee.Command command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public Referee.SSL_Referee.Command getCommand() {
      return command_;
    }
    
    // required uint32 command_counter = 5;
    public static final int COMMAND_COUNTER_FIELD_NUMBER = 5;
    private int commandCounter_;
    public boolean hasCommandCounter() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getCommandCounter() {
      return commandCounter_;
    }
    
    // required uint64 command_timestamp = 6;
    public static final int COMMAND_TIMESTAMP_FIELD_NUMBER = 6;
    private long commandTimestamp_;
    public boolean hasCommandTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getCommandTimestamp() {
      return commandTimestamp_;
    }
    
    // required .SSL_Referee.TeamInfo yellow = 7;
    public static final int YELLOW_FIELD_NUMBER = 7;
    private Referee.SSL_Referee.TeamInfo yellow_;
    public boolean hasYellow() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public Referee.SSL_Referee.TeamInfo getYellow() {
      return yellow_;
    }
    public Referee.SSL_Referee.TeamInfoOrBuilder getYellowOrBuilder() {
      return yellow_;
    }
    
    // required .SSL_Referee.TeamInfo blue = 8;
    public static final int BLUE_FIELD_NUMBER = 8;
    private Referee.SSL_Referee.TeamInfo blue_;
    public boolean hasBlue() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public Referee.SSL_Referee.TeamInfo getBlue() {
      return blue_;
    }
    public Referee.SSL_Referee.TeamInfoOrBuilder getBlueOrBuilder() {
      return blue_;
    }
    
    private void initFields() {
      packetTimestamp_ = 0L;
      stage_ = Referee.SSL_Referee.Stage.NORMAL_FIRST_HALF_PRE;
      stageTimeLeft_ = 0;
      command_ = Referee.SSL_Referee.Command.HALT;
      commandCounter_ = 0;
      commandTimestamp_ = 0L;
      yellow_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
      blue_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPacketTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommandCounter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommandTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYellow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getYellow().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBlue().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, packetTimestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, stage_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, stageTimeLeft_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, command_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, commandCounter_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, commandTimestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, yellow_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, blue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, packetTimestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, stage_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, stageTimeLeft_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, command_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, commandCounter_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, commandTimestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, yellow_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, blue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Referee.SSL_Referee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Referee.SSL_Referee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Referee.SSL_Referee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Referee.SSL_Referee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Referee.SSL_Referee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Referee.SSL_Referee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Referee.SSL_Referee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Referee.SSL_Referee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Referee.SSL_Referee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Referee.SSL_Referee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Referee.SSL_Referee prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Referee.SSL_RefereeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Referee.internal_static_SSL_Referee_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Referee.internal_static_SSL_Referee_fieldAccessorTable;
      }
      
      // Construct using Referee.SSL_Referee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getYellowFieldBuilder();
          getBlueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        packetTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        stage_ = Referee.SSL_Referee.Stage.NORMAL_FIRST_HALF_PRE;
        bitField0_ = (bitField0_ & ~0x00000002);
        stageTimeLeft_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = Referee.SSL_Referee.Command.HALT;
        bitField0_ = (bitField0_ & ~0x00000008);
        commandCounter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        commandTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (yellowBuilder_ == null) {
          yellow_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
        } else {
          yellowBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (blueBuilder_ == null) {
          blue_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
        } else {
          blueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Referee.SSL_Referee.getDescriptor();
      }
      
      public Referee.SSL_Referee getDefaultInstanceForType() {
        return Referee.SSL_Referee.getDefaultInstance();
      }
      
      public Referee.SSL_Referee build() {
        Referee.SSL_Referee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Referee.SSL_Referee buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Referee.SSL_Referee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Referee.SSL_Referee buildPartial() {
        Referee.SSL_Referee result = new Referee.SSL_Referee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packetTimestamp_ = packetTimestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stage_ = stage_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stageTimeLeft_ = stageTimeLeft_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.commandCounter_ = commandCounter_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.commandTimestamp_ = commandTimestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (yellowBuilder_ == null) {
          result.yellow_ = yellow_;
        } else {
          result.yellow_ = yellowBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (blueBuilder_ == null) {
          result.blue_ = blue_;
        } else {
          result.blue_ = blueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Referee.SSL_Referee) {
          return mergeFrom((Referee.SSL_Referee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Referee.SSL_Referee other) {
        if (other == Referee.SSL_Referee.getDefaultInstance()) return this;
        if (other.hasPacketTimestamp()) {
          setPacketTimestamp(other.getPacketTimestamp());
        }
        if (other.hasStage()) {
          setStage(other.getStage());
        }
        if (other.hasStageTimeLeft()) {
          setStageTimeLeft(other.getStageTimeLeft());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasCommandCounter()) {
          setCommandCounter(other.getCommandCounter());
        }
        if (other.hasCommandTimestamp()) {
          setCommandTimestamp(other.getCommandTimestamp());
        }
        if (other.hasYellow()) {
          mergeYellow(other.getYellow());
        }
        if (other.hasBlue()) {
          mergeBlue(other.getBlue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPacketTimestamp()) {
          
          return false;
        }
        if (!hasStage()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasCommandCounter()) {
          
          return false;
        }
        if (!hasCommandTimestamp()) {
          
          return false;
        }
        if (!hasYellow()) {
          
          return false;
        }
        if (!hasBlue()) {
          
          return false;
        }
        if (!getYellow().isInitialized()) {
          
          return false;
        }
        if (!getBlue().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packetTimestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              Referee.SSL_Referee.Stage value = Referee.SSL_Referee.Stage.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                stage_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              stageTimeLeft_ = input.readSInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              Referee.SSL_Referee.Command value = Referee.SSL_Referee.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                command_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              commandCounter_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              commandTimestamp_ = input.readUInt64();
              break;
            }
            case 58: {
              Referee.SSL_Referee.TeamInfo.Builder subBuilder = Referee.SSL_Referee.TeamInfo.newBuilder();
              if (hasYellow()) {
                subBuilder.mergeFrom(getYellow());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setYellow(subBuilder.buildPartial());
              break;
            }
            case 66: {
              Referee.SSL_Referee.TeamInfo.Builder subBuilder = Referee.SSL_Referee.TeamInfo.newBuilder();
              if (hasBlue()) {
                subBuilder.mergeFrom(getBlue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBlue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 packet_timestamp = 1;
      private long packetTimestamp_ ;
      public boolean hasPacketTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getPacketTimestamp() {
        return packetTimestamp_;
      }
      public Builder setPacketTimestamp(long value) {
        bitField0_ |= 0x00000001;
        packetTimestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearPacketTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetTimestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required .SSL_Referee.Stage stage = 2;
      private Referee.SSL_Referee.Stage stage_ = Referee.SSL_Referee.Stage.NORMAL_FIRST_HALF_PRE;
      public boolean hasStage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public Referee.SSL_Referee.Stage getStage() {
        return stage_;
      }
      public Builder setStage(Referee.SSL_Referee.Stage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        stage_ = value;
        onChanged();
        return this;
      }
      public Builder clearStage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stage_ = Referee.SSL_Referee.Stage.NORMAL_FIRST_HALF_PRE;
        onChanged();
        return this;
      }
      
      // optional sint32 stage_time_left = 3;
      private int stageTimeLeft_ ;
      public boolean hasStageTimeLeft() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getStageTimeLeft() {
        return stageTimeLeft_;
      }
      public Builder setStageTimeLeft(int value) {
        bitField0_ |= 0x00000004;
        stageTimeLeft_ = value;
        onChanged();
        return this;
      }
      public Builder clearStageTimeLeft() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stageTimeLeft_ = 0;
        onChanged();
        return this;
      }
      
      // required .SSL_Referee.Command command = 4;
      private Referee.SSL_Referee.Command command_ = Referee.SSL_Referee.Command.HALT;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public Referee.SSL_Referee.Command getCommand() {
        return command_;
      }
      public Builder setCommand(Referee.SSL_Referee.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000008);
        command_ = Referee.SSL_Referee.Command.HALT;
        onChanged();
        return this;
      }
      
      // required uint32 command_counter = 5;
      private int commandCounter_ ;
      public boolean hasCommandCounter() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getCommandCounter() {
        return commandCounter_;
      }
      public Builder setCommandCounter(int value) {
        bitField0_ |= 0x00000010;
        commandCounter_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommandCounter() {
        bitField0_ = (bitField0_ & ~0x00000010);
        commandCounter_ = 0;
        onChanged();
        return this;
      }
      
      // required uint64 command_timestamp = 6;
      private long commandTimestamp_ ;
      public boolean hasCommandTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getCommandTimestamp() {
        return commandTimestamp_;
      }
      public Builder setCommandTimestamp(long value) {
        bitField0_ |= 0x00000020;
        commandTimestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommandTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        commandTimestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required .SSL_Referee.TeamInfo yellow = 7;
      private Referee.SSL_Referee.TeamInfo yellow_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Referee.SSL_Referee.TeamInfo, Referee.SSL_Referee.TeamInfo.Builder, Referee.SSL_Referee.TeamInfoOrBuilder> yellowBuilder_;
      public boolean hasYellow() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public Referee.SSL_Referee.TeamInfo getYellow() {
        if (yellowBuilder_ == null) {
          return yellow_;
        } else {
          return yellowBuilder_.getMessage();
        }
      }
      public Builder setYellow(Referee.SSL_Referee.TeamInfo value) {
        if (yellowBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          yellow_ = value;
          onChanged();
        } else {
          yellowBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setYellow(
          Referee.SSL_Referee.TeamInfo.Builder builderForValue) {
        if (yellowBuilder_ == null) {
          yellow_ = builderForValue.build();
          onChanged();
        } else {
          yellowBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergeYellow(Referee.SSL_Referee.TeamInfo value) {
        if (yellowBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              yellow_ != Referee.SSL_Referee.TeamInfo.getDefaultInstance()) {
            yellow_ =
              Referee.SSL_Referee.TeamInfo.newBuilder(yellow_).mergeFrom(value).buildPartial();
          } else {
            yellow_ = value;
          }
          onChanged();
        } else {
          yellowBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearYellow() {
        if (yellowBuilder_ == null) {
          yellow_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
          onChanged();
        } else {
          yellowBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public Referee.SSL_Referee.TeamInfo.Builder getYellowBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getYellowFieldBuilder().getBuilder();
      }
      public Referee.SSL_Referee.TeamInfoOrBuilder getYellowOrBuilder() {
        if (yellowBuilder_ != null) {
          return yellowBuilder_.getMessageOrBuilder();
        } else {
          return yellow_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Referee.SSL_Referee.TeamInfo, Referee.SSL_Referee.TeamInfo.Builder, Referee.SSL_Referee.TeamInfoOrBuilder> 
          getYellowFieldBuilder() {
        if (yellowBuilder_ == null) {
          yellowBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Referee.SSL_Referee.TeamInfo, Referee.SSL_Referee.TeamInfo.Builder, Referee.SSL_Referee.TeamInfoOrBuilder>(
                  yellow_,
                  getParentForChildren(),
                  isClean());
          yellow_ = null;
        }
        return yellowBuilder_;
      }
      
      // required .SSL_Referee.TeamInfo blue = 8;
      private Referee.SSL_Referee.TeamInfo blue_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Referee.SSL_Referee.TeamInfo, Referee.SSL_Referee.TeamInfo.Builder, Referee.SSL_Referee.TeamInfoOrBuilder> blueBuilder_;
      public boolean hasBlue() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public Referee.SSL_Referee.TeamInfo getBlue() {
        if (blueBuilder_ == null) {
          return blue_;
        } else {
          return blueBuilder_.getMessage();
        }
      }
      public Builder setBlue(Referee.SSL_Referee.TeamInfo value) {
        if (blueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blue_ = value;
          onChanged();
        } else {
          blueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder setBlue(
          Referee.SSL_Referee.TeamInfo.Builder builderForValue) {
        if (blueBuilder_ == null) {
          blue_ = builderForValue.build();
          onChanged();
        } else {
          blueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder mergeBlue(Referee.SSL_Referee.TeamInfo value) {
        if (blueBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              blue_ != Referee.SSL_Referee.TeamInfo.getDefaultInstance()) {
            blue_ =
              Referee.SSL_Referee.TeamInfo.newBuilder(blue_).mergeFrom(value).buildPartial();
          } else {
            blue_ = value;
          }
          onChanged();
        } else {
          blueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder clearBlue() {
        if (blueBuilder_ == null) {
          blue_ = Referee.SSL_Referee.TeamInfo.getDefaultInstance();
          onChanged();
        } else {
          blueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      public Referee.SSL_Referee.TeamInfo.Builder getBlueBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getBlueFieldBuilder().getBuilder();
      }
      public Referee.SSL_Referee.TeamInfoOrBuilder getBlueOrBuilder() {
        if (blueBuilder_ != null) {
          return blueBuilder_.getMessageOrBuilder();
        } else {
          return blue_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Referee.SSL_Referee.TeamInfo, Referee.SSL_Referee.TeamInfo.Builder, Referee.SSL_Referee.TeamInfoOrBuilder> 
          getBlueFieldBuilder() {
        if (blueBuilder_ == null) {
          blueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Referee.SSL_Referee.TeamInfo, Referee.SSL_Referee.TeamInfo.Builder, Referee.SSL_Referee.TeamInfoOrBuilder>(
                  blue_,
                  getParentForChildren(),
                  isClean());
          blue_ = null;
        }
        return blueBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:SSL_Referee)
    }
    
    static {
      defaultInstance = new SSL_Referee(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:SSL_Referee)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SSL_Referee_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SSL_Referee_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SSL_Referee_TeamInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SSL_Referee_TeamInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rreferee.proto\"\335\010\n\013SSL_Referee\022\030\n\020packe" +
      "t_timestamp\030\001 \002(\004\022!\n\005stage\030\002 \002(\0162\022.SSL_R" +
      "eferee.Stage\022\027\n\017stage_time_left\030\003 \001(\021\022%\n" +
      "\007command\030\004 \002(\0162\024.SSL_Referee.Command\022\027\n\017" +
      "command_counter\030\005 \002(\r\022\031\n\021command_timesta" +
      "mp\030\006 \002(\004\022%\n\006yellow\030\007 \002(\0132\025.SSL_Referee.T" +
      "eamInfo\022#\n\004blue\030\010 \002(\0132\025.SSL_Referee.Team" +
      "Info\032\247\001\n\010TeamInfo\022\014\n\004name\030\001 \002(\t\022\r\n\005score" +
      "\030\002 \002(\r\022\021\n\tred_cards\030\003 \002(\r\022\035\n\021yellow_card" +
      "_times\030\004 \003(\rB\002\020\001\022\024\n\014yellow_cards\030\005 \002(\r\022\020",
      "\n\010timeouts\030\006 \002(\r\022\024\n\014timeout_time\030\007 \002(\r\022\016" +
      "\n\006goalie\030\010 \002(\r\"\321\002\n\005Stage\022\031\n\025NORMAL_FIRST" +
      "_HALF_PRE\020\000\022\025\n\021NORMAL_FIRST_HALF\020\001\022\024\n\020NO" +
      "RMAL_HALF_TIME\020\002\022\032\n\026NORMAL_SECOND_HALF_P" +
      "RE\020\003\022\026\n\022NORMAL_SECOND_HALF\020\004\022\024\n\020EXTRA_TI" +
      "ME_BREAK\020\005\022\030\n\024EXTRA_FIRST_HALF_PRE\020\006\022\024\n\020" +
      "EXTRA_FIRST_HALF\020\007\022\023\n\017EXTRA_HALF_TIME\020\010\022" +
      "\031\n\025EXTRA_SECOND_HALF_PRE\020\t\022\025\n\021EXTRA_SECO" +
      "ND_HALF\020\n\022\032\n\026PENALTY_SHOOTOUT_BREAK\020\013\022\024\n" +
      "\020PENALTY_SHOOTOUT\020\014\022\r\n\tPOST_GAME\020\r\"\322\002\n\007C",
      "ommand\022\010\n\004HALT\020\000\022\010\n\004STOP\020\001\022\020\n\014NORMAL_STA" +
      "RT\020\002\022\017\n\013FORCE_START\020\003\022\032\n\026PREPARE_KICKOFF" +
      "_YELLOW\020\004\022\030\n\024PREPARE_KICKOFF_BLUE\020\005\022\032\n\026P" +
      "REPARE_PENALTY_YELLOW\020\006\022\030\n\024PREPARE_PENAL" +
      "TY_BLUE\020\007\022\026\n\022DIRECT_FREE_YELLOW\020\010\022\024\n\020DIR" +
      "ECT_FREE_BLUE\020\t\022\030\n\024INDIRECT_FREE_YELLOW\020" +
      "\n\022\026\n\022INDIRECT_FREE_BLUE\020\013\022\022\n\016TIMEOUT_YEL" +
      "LOW\020\014\022\020\n\014TIMEOUT_BLUE\020\r\022\017\n\013GOAL_YELLOW\020\016" +
      "\022\r\n\tGOAL_BLUE\020\017"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SSL_Referee_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SSL_Referee_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SSL_Referee_descriptor,
              new java.lang.String[] { "PacketTimestamp", "Stage", "StageTimeLeft", "Command", "CommandCounter", "CommandTimestamp", "Yellow", "Blue", },
              Referee.SSL_Referee.class,
              Referee.SSL_Referee.Builder.class);
          internal_static_SSL_Referee_TeamInfo_descriptor =
            internal_static_SSL_Referee_descriptor.getNestedTypes().get(0);
          internal_static_SSL_Referee_TeamInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SSL_Referee_TeamInfo_descriptor,
              new java.lang.String[] { "Name", "Score", "RedCards", "YellowCardTimes", "YellowCards", "Timeouts", "TimeoutTime", "Goalie", },
              Referee.SSL_Referee.TeamInfo.class,
              Referee.SSL_Referee.TeamInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
